"""migration

Revision ID: ccd020aed1bd
Revises: b75a770502be
Create Date: 2024-10-30 17:49:12.228377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd020aed1bd'
down_revision: Union[str, None] = 'b75a770502be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_link', sa.String(length=1024), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('json_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_link', sa.String(length=1024), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_link', sa.String(length=1024), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_link', sa.String(length=1024), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_documents')
    op.drop_table('md_documents')
    op.drop_table('json_documents')
    op.drop_table('csv_documents')
    # ### end Alembic commands ###
